/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Mesh_tree_pineDefaultB: THREE.Mesh;
    Mesh_tree_pineDefaultB_1: THREE.Mesh;
  };
  materials: {
    woodBarkDark: THREE.MeshStandardMaterial;
    leafsDark: THREE.MeshStandardMaterial;
  };
};

export function TreeB(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/tree_pineDefaultB.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_tree_pineDefaultB.geometry}
          material={materials.woodBarkDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_tree_pineDefaultB_1.geometry}
          material={materials.leafsDark}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/tree_pineDefaultB.glb');
